import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

export interface CapitalCallNoticeData {
    fundName: string;
    callNumber: number;
    callDate: string;
    dueDate: string;
    purpose: string;
    totalAmount: string;
    items: Array<{
        investorName: string;
        committedAmount: string;
        callAmount: string;
        ownershipPct: string;
        status: string;
    }>;
}

export function generateCapitalCallPDF(data: CapitalCallNoticeData): void {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();

    const primaryColor: [number, number, number] = [17, 20, 29];
    const accentColor: [number, number, number] = [62, 92, 255];

    // Header
    doc.setFillColor(...primaryColor);
    doc.rect(0, 0, pageWidth, 50, 'F');

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(24);
    doc.setFont('helvetica', 'bold');
    doc.text(data.fundName, 20, 22);

    doc.setFontSize(14);
    doc.setFont('helvetica', 'normal');
    doc.text(`Capital Call Notice #${data.callNumber}`, 20, 35);

    doc.setFontSize(10);
    doc.text(`Issued: ${data.callDate}`, pageWidth - 20, 28, { align: 'right' });
    doc.text(`Due: ${data.dueDate}`, pageWidth - 20, 38, { align: 'right' });

    // Call Details
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Call Details', 20, 65);

    autoTable(doc, {
        startY: 70,
        head: [['Field', 'Value']],
        body: [
            ['Total Call Amount', data.totalAmount],
            ['Call Date', data.callDate],
            ['Due Date', data.dueDate],
            ['Purpose', data.purpose || 'Investment & Operations'],
        ],
        theme: 'plain',
        headStyles: {
            fillColor: accentColor,
            textColor: [255, 255, 255],
            fontStyle: 'bold',
        },
        styles: { fontSize: 11, cellPadding: 6 },
        columnStyles: {
            0: { fontStyle: 'bold', cellWidth: 60 },
        },
        margin: { left: 20, right: 20 },
    });

    const y1 = (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable.finalY || 130;

    // Investor Allocations
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Investor Allocations', 20, y1 + 15);

    if (data.items.length > 0) {
        autoTable(doc, {
            startY: y1 + 20,
            head: [['Investor', 'Commitment', 'Pro-Rata %', 'Call Amount', 'Status']],
            body: data.items.map((item) => [
                item.investorName,
                item.committedAmount,
                item.ownershipPct,
                item.callAmount,
                item.status,
            ]),
            theme: 'striped',
            headStyles: {
                fillColor: accentColor,
                textColor: [255, 255, 255],
                fontStyle: 'bold',
            },
            styles: { fontSize: 10, cellPadding: 6 },
            margin: { left: 20, right: 20 },
        });
    }

    // Footer
    const pageHeight = doc.internal.pageSize.getHeight();
    doc.setFontSize(9);
    doc.setTextColor(150, 150, 150);
    doc.text(
        `Generated by BlackGem - ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`,
        pageWidth / 2,
        pageHeight - 15,
        { align: 'center' }
    );

    const fileName = `${data.fundName.replace(/\s+/g, '_')}_Capital_Call_${data.callNumber}_${new Date().toISOString().split('T')[0]}.pdf`;
    doc.save(fileName);
}
