import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

export interface DashboardMetrics {
    fundName: string;
    totalAUM: string;
    aumChange: string;
    activeDeals: number;
    dealsChange: string;
    investors: number;
    investorsStatus: string;
    irrNet: string;
    irrChange: string;
    deals: Array<{
        name: string;
        stage: string;
        status: string;
    }>;
}

export function generateDashboardPDF(metrics: DashboardMetrics): void {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();

    // Colors
    const primaryColor: [number, number, number] = [17, 20, 29]; // #11141D
    const accentColor: [number, number, number] = [62, 92, 255]; // #3E5CFF

    // Header background
    doc.setFillColor(...primaryColor);
    doc.rect(0, 0, pageWidth, 45, 'F');

    // Fund name
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(24);
    doc.setFont('helvetica', 'bold');
    doc.text(metrics.fundName, 20, 25);

    // Report title and date
    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    doc.text('Dashboard Summary Report', 20, 35);

    const today = new Date().toLocaleDateString('en-US', {
        year: 'numeric',
        month: 'long',
        day: 'numeric',
    });
    doc.setFontSize(10);
    doc.text(today, pageWidth - 20, 35, { align: 'right' });

    // Key Metrics Section
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text('Key Performance Metrics', 20, 60);

    // Metrics table
    autoTable(doc, {
        startY: 65,
        head: [['Metric', 'Value', 'Change']],
        body: [
            ['Total AUM', metrics.totalAUM, metrics.aumChange],
            ['Active Deals', metrics.activeDeals.toString(), metrics.dealsChange],
            ['Investors', metrics.investors.toString(), metrics.investorsStatus],
            ['IRR (Net)', metrics.irrNet, metrics.irrChange],
        ],
        theme: 'striped',
        headStyles: {
            fillColor: accentColor,
            textColor: [255, 255, 255],
            fontStyle: 'bold',
        },
        styles: {
            fontSize: 11,
            cellPadding: 8,
        },
        columnStyles: {
            0: { fontStyle: 'bold', cellWidth: 60 },
            1: { cellWidth: 70 },
            2: { cellWidth: 50 },
        },
        margin: { left: 20, right: 20 },
    });

    // Deal Pipeline Section
    const finalY = (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable.finalY || 120;

    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text('Deal Pipeline', 20, finalY + 20);

    if (metrics.deals.length > 0) {
        autoTable(doc, {
            startY: finalY + 25,
            head: [['Deal Name', 'Stage', 'Status']],
            body: metrics.deals.map((deal) => [deal.name, deal.stage, deal.status]),
            theme: 'striped',
            headStyles: {
                fillColor: accentColor,
                textColor: [255, 255, 255],
                fontStyle: 'bold',
            },
            styles: {
                fontSize: 11,
                cellPadding: 8,
            },
            margin: { left: 20, right: 20 },
        });
    } else {
        doc.setFontSize(11);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(100, 100, 100);
        doc.text('No active deals in pipeline.', 20, finalY + 30);
    }

    // Footer
    const pageHeight = doc.internal.pageSize.getHeight();
    doc.setFontSize(9);
    doc.setTextColor(150, 150, 150);
    doc.text(
        `Generated by BlackGem - ${today}`,
        pageWidth / 2,
        pageHeight - 15,
        { align: 'center' }
    );

    // Download
    const fileName = `${metrics.fundName.replace(/\s+/g, '_')}_Dashboard_${new Date().toISOString().split('T')[0]}.pdf`;
    doc.save(fileName);
}
