import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

export interface DistributionNoticeData {
    fundName: string;
    distributionNumber: number;
    distributionDate: string;
    totalAmount: string;
    returnOfCapital: string;
    realizedGains: string;
    dividends: string;
    interest: string;
    items: Array<{
        investorName: string;
        grossAmount: string;
        netAmount: string;
        ownershipPct: string;
        status: string;
    }>;
}

export function generateDistributionPDF(data: DistributionNoticeData): void {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();

    const primaryColor: [number, number, number] = [17, 20, 29];
    const accentColor: [number, number, number] = [62, 92, 255];
    const successColor: [number, number, number] = [5, 150, 105]; // emerald-600

    // Header
    doc.setFillColor(...primaryColor);
    doc.rect(0, 0, pageWidth, 50, 'F');

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(24);
    doc.setFont('helvetica', 'bold');
    doc.text(data.fundName, 20, 22);

    doc.setFontSize(14);
    doc.setFont('helvetica', 'normal');
    doc.text(`Distribution Notice #${data.distributionNumber}`, 20, 35);

    doc.setFontSize(10);
    doc.text(`Date: ${data.distributionDate}`, pageWidth - 20, 35, { align: 'right' });

    // Distribution Summary
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Distribution Summary', 20, 65);

    autoTable(doc, {
        startY: 70,
        head: [['Component', 'Amount']],
        body: [
            ['Return of Capital', data.returnOfCapital || '$0'],
            ['Realized Gains', data.realizedGains || '$0'],
            ['Dividends', data.dividends || '$0'],
            ['Interest', data.interest || '$0'],
        ],
        foot: [['Total Distribution', data.totalAmount]],
        theme: 'plain',
        headStyles: {
            fillColor: accentColor,
            textColor: [255, 255, 255],
            fontStyle: 'bold',
        },
        footStyles: {
            fillColor: successColor,
            textColor: [255, 255, 255],
            fontStyle: 'bold',
        },
        styles: { fontSize: 11, cellPadding: 6 },
        columnStyles: {
            0: { fontStyle: 'bold', cellWidth: 80 },
        },
        margin: { left: 20, right: 20 },
    });

    const y1 = (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable.finalY || 140;

    // Investor Allocations
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Investor Allocations', 20, y1 + 15);

    if (data.items.length > 0) {
        autoTable(doc, {
            startY: y1 + 20,
            head: [['Investor', 'Pro-Rata %', 'Gross Amount', 'Net Amount', 'Status']],
            body: data.items.map((item) => [
                item.investorName,
                item.ownershipPct,
                item.grossAmount,
                item.netAmount,
                item.status,
            ]),
            theme: 'striped',
            headStyles: {
                fillColor: accentColor,
                textColor: [255, 255, 255],
                fontStyle: 'bold',
            },
            styles: { fontSize: 10, cellPadding: 6 },
            margin: { left: 20, right: 20 },
        });
    }

    // Footer
    const pageHeight = doc.internal.pageSize.getHeight();
    doc.setFontSize(9);
    doc.setTextColor(150, 150, 150);
    doc.text(
        `Generated by BlackGem - ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`,
        pageWidth / 2,
        pageHeight - 15,
        { align: 'center' }
    );

    const fileName = `${data.fundName.replace(/\s+/g, '_')}_Distribution_${data.distributionNumber}_${new Date().toISOString().split('T')[0]}.pdf`;
    doc.save(fileName);
}
