import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

export interface QuarterlyUpdatePDFData {
    fundName: string;
    year: number;
    quarter: number;
    periodStart: Date;
    periodEnd: Date;
    sections: Array<{
        key: string;
        title: string;
        content: string;
    }>;
}

const primaryColor: [number, number, number] = [17, 20, 29]; // #11141D
const accentColor: [number, number, number] = [62, 92, 255]; // #3E5CFF

function addFooter(doc: jsPDF, pageWidth: number, pageHeight: number, date: string, pageNum: number): void {
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(148, 163, 184);
    doc.text('Confidential — For Investor Use Only', 20, pageHeight - 12);
    doc.text(`Generated by BlackGem — ${date}`, 20, pageHeight - 18);
    doc.text(`Page ${pageNum}`, pageWidth - 20, pageHeight - 12, { align: 'right' });
}

function getSection(sections: QuarterlyUpdatePDFData['sections'], key: string): string {
    const section = sections.find((s) => s.key === key);
    return section?.content || '';
}

function getSectionTitle(sections: QuarterlyUpdatePDFData['sections'], key: string): string {
    const section = sections.find((s) => s.key === key);
    return section?.title || '';
}

function checkPageBreak(
    doc: jsPDF,
    currentY: number,
    requiredSpace: number,
    pageHeight: number,
    pageWidth: number,
    today: string,
    pageNumberRef: { value: number }
): number {
    if (currentY + requiredSpace > pageHeight - 30) {
        addFooter(doc, pageWidth, pageHeight, today, pageNumberRef.value);
        doc.addPage();
        pageNumberRef.value += 1;
        return 20;
    }
    return currentY;
}

export function generateQuarterlyUpdatePDF(data: QuarterlyUpdatePDFData): void {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const pageNumberRef = { value: 1 };

    const today = new Date().toLocaleDateString('en-US', {
        year: 'numeric',
        month: 'long',
        day: 'numeric',
    });

    const periodLabel = `Q${data.quarter} ${data.year}`;
    const periodStart = new Date(data.periodStart).toLocaleDateString('en-US', {
        month: 'short',
        day: 'numeric',
        year: 'numeric',
    });
    const periodEnd = new Date(data.periodEnd).toLocaleDateString('en-US', {
        month: 'short',
        day: 'numeric',
        year: 'numeric',
    });

    // =========================================================================
    // COVER PAGE
    // =========================================================================

    // Dark header bar
    doc.setFillColor(...primaryColor);
    doc.rect(0, 0, pageWidth, 70, 'F');

    // Fund name
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(24);
    doc.setFont('helvetica', 'bold');
    doc.text(data.fundName, 20, 28);

    // Period
    doc.setFontSize(16);
    doc.setFont('helvetica', 'normal');
    doc.text(periodLabel, 20, 42);

    // Report title
    doc.setFontSize(12);
    doc.text('Quarterly Investor Update', 20, 56);

    // Generation date below header
    doc.setTextColor(148, 163, 184);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`Generated ${today}`, 20, 85);

    // Period range
    doc.text(`Reporting Period: ${periodStart} — ${periodEnd}`, 20, 95);

    // Accent line
    doc.setDrawColor(...accentColor);
    doc.setLineWidth(1);
    doc.line(20, 78, 80, 78);

    addFooter(doc, pageWidth, pageHeight, today, pageNumberRef.value);

    // =========================================================================
    // LETTER FROM THE PRINCIPALS
    // =========================================================================

    const letterContent = getSection(data.sections, 'letter');
    if (letterContent.trim()) {
        doc.addPage();
        pageNumberRef.value += 1;
        let currentY = 20;

        const letterTitle = getSectionTitle(data.sections, 'letter') || 'Letter from the Manager';
        doc.setTextColor(0, 0, 0);
        doc.setFontSize(16);
        doc.setFont('helvetica', 'bold');
        doc.text(letterTitle, 20, currentY);
        currentY += 10;

        // Accent underline
        doc.setDrawColor(...accentColor);
        doc.setLineWidth(0.5);
        doc.line(20, currentY, 80, currentY);
        currentY += 8;

        doc.setTextColor(60, 60, 60);
        doc.setFontSize(10);
        doc.setFont('helvetica', 'normal');

        const letterLines = doc.splitTextToSize(letterContent, pageWidth - 40);
        for (let i = 0; i < letterLines.length; i++) {
            currentY = checkPageBreak(doc, currentY, 6, pageHeight, pageWidth, today, pageNumberRef);
            doc.text(letterLines[i], 20, currentY);
            currentY += 5;
        }

        addFooter(doc, pageWidth, pageHeight, today, pageNumberRef.value);
    }

    // =========================================================================
    // FUND SUMMARY
    // =========================================================================

    const fundSummaryContent = getSection(data.sections, 'fund_summary');
    if (fundSummaryContent.trim()) {
        doc.addPage();
        pageNumberRef.value += 1;
        let currentY = 20;

        const fundSummaryTitle = getSectionTitle(data.sections, 'fund_summary') || 'Fund Summary';
        doc.setTextColor(0, 0, 0);
        doc.setFontSize(16);
        doc.setFont('helvetica', 'bold');
        doc.text(fundSummaryTitle, 20, currentY);
        currentY += 10;

        // Parse lines into table rows
        const summaryLines = fundSummaryContent
            .split('\n')
            .map((line) => line.trim())
            .filter((line) => line.length > 0);

        const summaryRows: [string, string][] = summaryLines.map((line) => {
            const colonIndex = line.indexOf(':');
            if (colonIndex > -1) {
                return [line.substring(0, colonIndex).trim(), line.substring(colonIndex + 1).trim()];
            }
            return [line, ''];
        });

        autoTable(doc, {
            startY: currentY + 4,
            head: [['Metric', 'Value']],
            body: summaryRows,
            theme: 'striped',
            headStyles: { fillColor: accentColor, textColor: [255, 255, 255], fontStyle: 'bold' },
            styles: { fontSize: 10, cellPadding: 6 },
            columnStyles: { 0: { fontStyle: 'bold', cellWidth: 80 }, 1: { cellWidth: 80 } },
            margin: { left: 20, right: 20 },
        });

        addFooter(doc, pageWidth, pageHeight, today, pageNumberRef.value);
    }

    // =========================================================================
    // PORTFOLIO COMPANY UPDATES
    // =========================================================================

    const portfolioContent = getSection(data.sections, 'portfolio_update');
    if (portfolioContent.trim()) {
        doc.addPage();
        pageNumberRef.value += 1;
        let currentY = 20;

        const portfolioTitle = getSectionTitle(data.sections, 'portfolio_update') || 'Portfolio Company Updates';
        doc.setTextColor(0, 0, 0);
        doc.setFontSize(16);
        doc.setFont('helvetica', 'bold');
        doc.text(portfolioTitle, 20, currentY);
        currentY += 10;

        const portfolioLines = portfolioContent
            .split('\n')
            .map((line) => line.trim())
            .filter((line) => line.length > 0);

        // Parse each line as company: details
        const portfolioRows: [string, string][] = portfolioLines.map((line) => {
            const colonIndex = line.indexOf(':');
            if (colonIndex > -1) {
                return [line.substring(0, colonIndex).trim(), line.substring(colonIndex + 1).trim()];
            }
            return [line, ''];
        });

        autoTable(doc, {
            startY: currentY + 4,
            head: [['Company', 'Details']],
            body: portfolioRows,
            theme: 'striped',
            headStyles: { fillColor: accentColor, textColor: [255, 255, 255], fontStyle: 'bold' },
            styles: { fontSize: 10, cellPadding: 6 },
            columnStyles: { 0: { fontStyle: 'bold', cellWidth: 60 } },
            margin: { left: 20, right: 20 },
        });

        addFooter(doc, pageWidth, pageHeight, today, pageNumberRef.value);
    }

    // =========================================================================
    // CAPITAL ACTIVITY
    // =========================================================================

    const capitalContent = getSection(data.sections, 'capital_summary');
    if (capitalContent.trim()) {
        doc.addPage();
        pageNumberRef.value += 1;
        let currentY = 20;

        const capitalTitle = getSectionTitle(data.sections, 'capital_summary') || 'Capital Activity';
        doc.setTextColor(0, 0, 0);
        doc.setFontSize(16);
        doc.setFont('helvetica', 'bold');
        doc.text(capitalTitle, 20, currentY);
        currentY += 10;

        const capitalLines = capitalContent
            .split('\n')
            .map((line) => line.trim())
            .filter((line) => line.length > 0);

        const capitalRows: [string, string][] = capitalLines.map((line) => {
            const colonIndex = line.indexOf(':');
            if (colonIndex > -1) {
                return [line.substring(0, colonIndex).trim(), line.substring(colonIndex + 1).trim()];
            }
            return [line, ''];
        });

        autoTable(doc, {
            startY: currentY + 4,
            head: [['Metric', 'Amount']],
            body: capitalRows,
            theme: 'striped',
            headStyles: { fillColor: accentColor, textColor: [255, 255, 255], fontStyle: 'bold' },
            styles: { fontSize: 10, cellPadding: 6 },
            columnStyles: { 0: { fontStyle: 'bold', cellWidth: 80 }, 1: { cellWidth: 80 } },
            margin: { left: 20, right: 20 },
        });

        addFooter(doc, pageWidth, pageHeight, today, pageNumberRef.value);
    }

    // =========================================================================
    // LOOKING AHEAD
    // =========================================================================

    const lookingAheadContent = getSection(data.sections, 'looking_ahead');
    if (lookingAheadContent.trim()) {
        doc.addPage();
        pageNumberRef.value += 1;
        let currentY = 20;

        const lookingAheadTitle = getSectionTitle(data.sections, 'looking_ahead') || 'Looking Ahead';
        doc.setTextColor(0, 0, 0);
        doc.setFontSize(16);
        doc.setFont('helvetica', 'bold');
        doc.text(lookingAheadTitle, 20, currentY);
        currentY += 10;

        // Accent underline
        doc.setDrawColor(...accentColor);
        doc.setLineWidth(0.5);
        doc.line(20, currentY, 80, currentY);
        currentY += 8;

        doc.setTextColor(60, 60, 60);
        doc.setFontSize(10);
        doc.setFont('helvetica', 'normal');

        const aheadLines = doc.splitTextToSize(lookingAheadContent, pageWidth - 40);
        for (let i = 0; i < aheadLines.length; i++) {
            currentY = checkPageBreak(doc, currentY, 6, pageHeight, pageWidth, today, pageNumberRef);
            doc.text(aheadLines[i], 20, currentY);
            currentY += 5;
        }

        addFooter(doc, pageWidth, pageHeight, today, pageNumberRef.value);
    }

    // =========================================================================
    // DISCLAIMER
    // =========================================================================

    // Add disclaimer on the last page
    const lastPageNum = doc.getNumberOfPages();
    doc.setPage(lastPageNum);
    const lastY = pageHeight - 35;
    doc.setFontSize(8);
    doc.setFont('helvetica', 'italic');
    doc.setTextColor(148, 163, 184);
    doc.text(
        'This report is confidential and intended solely for the use of the fund\'s limited partners and authorized personnel.',
        20,
        lastY,
        { maxWidth: pageWidth - 40 }
    );

    // =========================================================================
    // APPLY FOOTERS TO ALL PAGES
    // =========================================================================

    const totalPages = doc.getNumberOfPages();
    for (let i = 1; i <= totalPages; i++) {
        doc.setPage(i);
        addFooter(doc, pageWidth, pageHeight, today, i);
    }

    // =========================================================================
    // DOWNLOAD
    // =========================================================================

    const fileName = `${data.fundName.replace(/\s+/g, '_')}_Q${data.quarter}_${data.year}_Quarterly_Update.pdf`;
    doc.save(fileName);
}
